### ISSUE TITLE
Data element circular reference detected

### ISSUE THREAD

**Issue by alcazes** [adobe/reactor-extension-core-edge#7] opened 2023-10-31 11:47 UTC
### Expected Behaviour

We should be able to reference a data element inside another data element

### Actual Behaviour

Error

```json
{
    "name": "evaluatingRule",
    "timestampMs": 1698750499741,
    "attributes": {
        "logLevel": "error"
    },
    "messages": [
        "🚀",
        "Failed to execute \"Make Fetch Call\". Data element circular reference detected: platform -> eventType -> lifecycleShortCode -> eventType \n Error: Failed to execute \"Make Fetch Call\". Data element circular reference detected: platform -> eventType -> lifecycleShortCode -> eventType\n    at worker.js:1:6395\n    at worker.js:1:6063\n    at Array.map (<anonymous>)\n    at worker.js:1:5979\n    at getSettings (worker.js:1:10866)\n    at worker.js:1:6602\n    at worker.js:1:6063\n    at Array.map (<anonymous>)\n    at worker.js:1:5979\n    at getSettings (worker.js:1:13752)"
    ],
    "logLevel": "log",
    "context": {
        "ruleId": "RL8ff0fa7212044c8292174187be01e09f"
    }
},
```

#### Sample Code that illustrates the problem

There seems to be a bug in Adobe Event Forwarding:
![Event Forwarding Error](https://github.com/adobe/reactor-extension-core-edge/assets/8456933/045b15cc-26c3-4000-906a-4399a09854b2)

Data Elements are as follow:
![data elements](https://github.com/adobe/reactor-extension-core-edge/assets/8456933/769c7d4b-33af-4f11-ad35-5ee3418de2a4)
 
platform
![platform](https://github.com/adobe/reactor-extension-core-edge/assets/8456933/1c58053f-419d-4a73-a7d9-a8a5506b47ee)

eventType
![eventType](https://github.com/adobe/reactor-extension-core-edge/assets/8456933/eae4e1b3-543d-49a2-b769-fb117f131321)
 
lifecycleShortCode
![lifecycleShortCode](https://github.com/adobe/reactor-extension-core-edge/assets/8456933/a54f2d88-37e9-42d4-9d71-04689ff128f1)

**Comment by dompuiu** [comment] 2023-11-02 15:58
This is a duplicate of https://github.com/adobe/reactor-extension-cloud-connector-edge/issues/5. The issue is in `reactor-turbine-edge`.

**Closed by dompuiu** 2023-11-02 15:58 UTC
